/*
 * Copyright (c) 2000-2025, 2026 S. Bhatnagar (bhatnagar dot sanjay at gmail dot com)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * $Id: clparseVal.c,v 2.0 1998/11/11 07:13:02 sanjay Exp sanjay $ */

#ifndef CLPARSEVAL_H
#define CLPARSEVAL_H
#include <cl.h>

//#include <clhashdefines.h>
//#include <cllib.h>
//#include <string>
//#include <vector>
//#include <sstream>
//#include <clError.h>

template <class T>
int clparseVal(Symbol *S, int *Which, T &d)
{
  unsigned int N = _ABS(*Which);
HANDLE_EXCEPTIONS(
  if (S != NULL)
    {
      if (N > S->NVals) return 0;
      if (ISSET(S->Attributes,CL_BOOLTYPE))
	{
	  int retVal;
	  string val(S->Val[N-1]);
	  if ((retVal=clIsTrue(val))==1) d=1;
	  else if ((retVal=clIsFalse(val))==1) d=0;
	  //*d = clIsTrue(val);
	  if (retVal == CL_UNKNOWNBOOL)
	    {
	      clBoolParsingError clExcp;
	      reportParseError(clExcp, *S, N-1);
	    }
	}
      else
	{
	  double dd=d;
	  int n=calc((char *)S->Val[N-1].c_str(),&dd);
	  d=dd;
	  if (n < 0)
	    {
	      clNumParsingError clExcp;
	      reportParseError(clExcp,*S, N-1);
	    }
	}
      return 1;
    }
  else return CL_FAIL;
)
}

//
// Delete the function generated by the template above for string.
// The specific implementation of this is in clparseVal.cc
//
template <>
int clparseVal<std::string>(Symbol *S, int *Which, string& val)=delete;

int clparseVal(Symbol *S, int *which, string& val);

#endif
